### ISSUE TITLE
The toggle button doesn't show in the camera app (14.2, Taurine, iPhone 12)

### ISSUE THREAD

**Issue by SKDemon820** [PoomSmart/Record--n--Torch#2]
Online there seems to be a mixed bag of results with the tweak.  For the majority it works fine, but for others like me the icon to toggle flash simply doesn't show, even with all other tweaks disabled (As you can see in the attached image it isn't there).  I'm not sure what could be causing this since people with seemingly identical setups encounter no issue, but any help would be appreciated.

![image](https://user-images.githubusercontent.com/62918850/166836730-5472ad7e-0a77-4d1e-96a8-35999b56e00c.png)

**Comment by PoomSmart** [comment]
@SKDemon820 Can you uninstall the tweak then install this one instead to see if it works?

[com.ps.recordntorch_1.8.0_iphoneos-arm.deb.zip](https://github.com/PoomSmart/Record--n--Torch/files/8628533/com.ps.recordntorch_1.8.0_iphoneos-arm.deb.zip)

(Unzip this file and install the deb via Filza)

**Comment by SKDemon820** [comment]
Hey, sorry for the late reply I didn't see the notification.  It doesn't appear to be working, there's still no toggle button.

**Comment by PoomSmart** [comment]
@SKDemon820 Can you try this version?
[com.ps.recordntorch_1.8.0_iphoneos-arm.deb.zip](https://github.com/PoomSmart/Record--n--Torch/files/8697812/com.ps.recordntorch_1.8.0_iphoneos-arm.deb.zip)

**Comment by SKDemon820** [comment]
That one has the toggle, but it doesn’t seem to do anything.  The flash stays on whatever status it was at when the video started, regardless of if the toggle is on or off.

**Comment by PoomSmart** [comment]
@SKDemon820 This one should finally work?
[com.ps.recordntorch_1.8.0_iphoneos-arm.deb.zip](https://github.com/PoomSmart/Record--n--Torch/files/8708321/com.ps.recordntorch_1.8.0_iphoneos-arm.deb.zip)

**Comment by SKDemon820** [comment]
No same thing, the toggle is shown and intractable but the flash doesn't actually change :/

**Comment by PoomSmart** [comment]
Does the new version (1.8.1) fix it?

**Comment by U75258** [comment]
iPhone12pro 14.3 taurine don't work ,Clicking the flash button does not turn on the flashlight.
