### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by U75258** [PoomSmart/Record--n--Torch#3]
iPhone12pro 14.3 taurine don't work ,Clicking the flash button does not turn on the flashlight.
I remember it was working two or three months ago and then something went wrong with the environment I cleared a jailbreak until today I reinstalled it and it doesn't work anymore Disabled other tweaks as well.

**Comment by U75258** [comment]
it doesn't show up in settings

**Comment by PoomSmart** [comment]
Fixed in 1.8.2
